

def a_dict():
	dict_a = {"abandon (verb)": ["hagar", "tarak"], "abandoned (adj)": "matrook", "abandonment (noun)": "tark", 
	"abbey (noun s)": "deer", "abbreviation (noun s)": "iKtiSaar", "abdomen (noun s)": "baTn",
	"abhor (verb inf)": ["MaQat", "kirih"], "abide - tolerate (verb inf)": "istahmil",
	"ability (noun s)": "Qudra", "able (adj, verb)": ["idir", "airif"], "abnormal (adj)": "mish TabeeAi",
	"abode (noun s)": "manzil", "abolish (verb inf)": "laGa", "abort": "ighaaD",
	"about - approximately (adv)": ["hawaeli", "ta'reeban"], "about - concerning (prep)": ["iza", "Aan", "fi", "Aala"],
	"above": ["foo", "aAla"], "abrasive": "ma'shooT", "abroad": ["Kaerig", "barra"], 
	"abrupt - sudden (adj)": "mufaegi'", "abrupt - short, rude (adj)": "haed", 
	"abruptly (adv)": "fag'aa", "absence (n s)": "Giyaeb", 
	"absent  - be absent from (vi inf)": "Gaeb Aan", "absent (adj)": "Gaeyib",
	"absent minded": ["masTool", "sarhaen"], "absolute (adj)": "muTla'", "absolutely": ["kullayyan", "Kaalis", "giddan"],
	"abuse - insult (verb inf)": ["shatam", "bahdil", "ihaena", "tahz"], 
	"abyss (noun s)": "Garee'", "Ethiopia (noun)": "ilhabasha", "academic (adj)": "'akadeemi",
	"accelerator (pedal) (noun)": "baddael banzeen", "accent (noun)": "lakna", 
	"accept - agree (verb inf)": "'ibil", "accept - a situation (v inf)": "riDi",
	"acceptable (adj)": "ma'bool", "acceptance (noun)": "Qubool", "access - movement: in and out (n invar)": "madKal",
	"access - movement: contain (v inf)": "daKal", "accident": "haedith", 
	"accidentally (adv)": "unintentionally - min Geer 'aSd", "accommodate (verb inf)": "saKan",
	"accompany - go with (v inf)": "raah maAa", "accomplice": "muTaAahhid", "accomplish (v inf)": "ha''a'",
	"according to": "hasab", "accordingly (adv)": "wa aAla zalik", "account - financial (n s)": "hisaeb",
	"account - explain (v inf)": "sharah", "accountant (n s)": "muhaesib", "accounting (n)": "Alim ilmuhasba",
	"accumulate (v inf)": "gammaA", "accurate (adj)": "daQeeQ", "accurately (adv)": "biilZabT",
	"accusation (n s)": ["tuhma", "shakwa"], "accuse (v inf)": "'ittaham", "accused (adj)": "muttaham",
	"accustomed - be accustomed to (vi inf)": "itAawwid", "ace - cards": "'es", "ache": "'alam",
	"achieve (v inf)": "ha''a'", "achievement (n s)": "'ingaez", "acid": "hamDi", "acidic": "haamiD",
	"acidity": "humooDa", "acknowledge": "'aAtaraf", "acquaint": "Aarraf bi", "acquaintance - make one": "'itAarraf bi",
	"acquaintance - person": "maArifa", "across": "Aaddi", "across from": "uSaad",
	"act - take action/behave": ["itSarraf", "Aamal"], "act - in a play": "maththil", 
	"act the fool": "Aakk", "acting": "tamtheel", "acting gay": "miKawalin", "action (n s)": ["fiAl", "taSarraf"],
	"active": "nusheeT", "activity": "nashaaT", "actor": "mumaththil", "actual - fact": ["haeli", "ha'ee'i"],
	"actually": "fi ilha'ee'a", "add - put in": ["Daaf", "zawwid", "zaed", "haTT"], "add- numbers": "gammaA",
	"addict (noun s)": "mudmin", "addiction (n s)": "'idmaen", "addition": "iDaafa",
	"additional": "kamaen", "additionally": "biil'iDaafa", "address": "Ainwaen",
	"adequate - sufficient": "kifaeya", "adequate - suitable": "munaesib", "admire": "aAgab",
	"admirer": "muAgab", "admit - accept": "'ibil", "admit - own up": "'iAtaraf",
	"adore (v inf)": "'ithawas", "adult": ["baeliG", "kibeer"], "adulterer": "zaeni", "adultery": "zina",
	"advice (noun)": "naSeeha", "advice - ask for advice": "shaewir", "advise": "naSah",
	"aerial": "'iryal", "aeroplane": "Tayaara", "affair - relationship": "AilaaQa", 
	"affair - matter": "mawDwaA", "affect": "'aththar fi", "affected": "maayis",
	"affection": "t'atheer", "afraid": "Kaayif", "I'm afraid so": "lil'asaf", 
	"I'm afraid that": "'ana Kaeyif min", "africa": "afreeQya", "african": "afreeQi",
	"after": "baAd ma", "after that": ["baAd kida", "baAdeen"], "afterlife": "il'eKira",
	"afternoon": "baAd ilDuhr", "afterwards": ["baAdeen", "baAd kida"], "again": "thaeni",
	"against - leaning on": "Aala", "against - opposing": "Didd", "against - opposite": "Aaks",
	"against the wishes of": "GaSbin Aan", "age": "sin", "aggression": "Audwaen", 
	"aggressive": "Audwaeni", "(be) aghast (vi inf)": "ballim", "agitate": "sarbaA",
	"agitated": "mitAaSab", "agree (on)": "waefi Aala", "agree (with)": "ittafa' maAa",
	"agree": "waefi'", "agreeable": "laTeef", "agreed": "maeshi", "agreed?": "'ittafa'nae?",
	"agreeing": "muwaefi'", "agreement": "'itifae", "aid (n s)": "aAaen",
	"aid (v inf)": "saeAid", "aim - purpose (n s)": "hadaf", "aim (v inf)": "saAa",
	"aimless - about person lacking purpose": "mitKabbaT", "air": "hawa'", 
	"air conditioning": "takyeef", "air vent": "hawwaeya", "aircraft": "Tayaara",
	"airline": "sharikit Tayaraan", "airport": "maTaar", "aisle": "mamarr", 
	"alarm clock (n s)": "minabbih", "alarm (n s)": "tanbeeh", "album": "'alboom",
	"alcohol": "Kamra", "Alexandria": "il'iskandiriyya", "algebra": "Ailm ilgabr",
	"alibi": "hagga", "alien - from space": "ka'n faDa", "alien - foreign": "'agnabi",
	"alive": "Aaeyish", "all - every": "kull", "all - everything": "kull haega",
	"all (adj)": "gameeA", "all - any": "ai", "all day": ["Tool ilnahaar", "Tool ilyoom"],
	"all my life": "Tool Aumri", "all night": "Tool illeel", "all of us": "kullina",
	"all over again": "min 'awwil wi gideed", "all the time": "Tool ilwa't", 
	"all week": "Tool il'usbooA", "all your life": "Tool Aumrak", "allow - someone something": "Kalla",
	"allow - someone to do something": "samahly bi", "allowance:": "maSroof", "almond": "looz",
	"almost - approximately": "ta'reeban", "alone": "liwahduh", "alphabet": "abgadiyya",
	"already": "ba'a", "alright": "kuwayis", "also": "kamaen", "alter": "Gayyar",
	"alternative": "badeel", "alternatively": "badeelan", "although": "maAa 'inn",
	"altogether - completely": "tamaeman", "always": ["tamalli", "dayman", "Aala Tool"],
	"am": "Sabbahan", "amateur": "haewi", "amaze": "gannin", "amazed": "'indahash", 
	"amazement": "Aageeba", "amazing - strange": "Aageeb", "amazing - remarkable": "mudhish",
	"amber": "Aanbar", "ambition": "Tumooh", "ambitious": "Tamooh", "ambulance": "Aarabiyit il'isAaef",
	"america": "'amreeka", "american": "'amreeki", "amongst": "minhum", "amount": "mablaG",
	"amphibious": "barrimae'i", "amputate": "batar", "amulet": "tameema", "amuse": "salla",
	"amusing": "musalli", "analyse": "hallil", "analysis": "tahleel", "analyst": "muhallil",
	"ancient": "'adeem", "and - also": "wa", "and - with": "bi", "and - then": "wa",
	"and then": "wa", "anew": "min gideed", "angel": "malaek", "anger (n invar)": "GaDab",
	"angle": "zawya", "(be) angry (about) (vi inf)": "'itnarfiz Aala", "(get) angry (v inf)": "GiDib",
	"(make so.) angry (v inf)": "GaaZ", "very angry": "GaDbaan min", "animal": "hayawaen",
	"large domestic animal (farm)": "biheem", "ankle": "'ankil", "anniversary": "Aeed",
	"annoy": "Daeyi'", "annoyance": "mutAib", "(get) annoyed": "'itDaeyi'", "annoyed": "miDaeyi'",
	"annoying": "mustafizz", "another - same": "thaeni", "another - different": "Geer",
	"answer": ["radd", "'igaeba"], "ant": "naml", "anticipate - expect": "tawaQQaA", 
	"anus": "fathit ilsharag", "anxiety": ["shagan", "mubaela"], "anxious": "'al'aen",
	"any": "'ai", "any more": "baAd kida", "anybody": ["'ai shaKs", "'ayi hadd"],
	"anyone": ["ayi hadd", "ai shaKs", "ayi insaen"], "anything": ["ayi haega", "ayi sh"],
	"anytime": "'ai wa't", "anyway": "Aala ilAumoom", "anywhere": "'ai makaen", "apart": "'abaAd",
	"apartment": "sha''a", "apologize": ["'iAtizir", "'aAtizir"], "apology": "'aAtizaar",
	"apparent": "Zaahir", "apparently": ["yiZhar 'inn", "TiliAw"], "appeal - attraction": "'aAgab",
	"appeal - plead": "'itragga", "appear - seem": "baen", "appearance": ["maZhar", "shakl", "manZar"],
	"appearing": "Zuhoor", "appears": "baeyin", "appetizers": "mazza", "apple": "tuffaeh",
	"apply": "'addim", "appreciate": "'addar", "appreciation": "ta'deer", "approach": "'arrab min",
	"appropriate": ["Sahh", "munaesib"], "approval": "muwaf'a", "approve": "waefi' Aala",
	"approximately": "ta'reeban", "apricot": "mishmish", "april": "'abreel", "apron": "maryala",
	"arab": "Aarabi", "arabic": "Aarabi", "archbishop": "baTiryark", "architect": "muhandis miAmaeri",
	"architecture": "ilhandasa ilmiAmaariyya", "area - region": ["manTiQa", "hitta"],
	"argue - discuss": "nae'ish", "argue - disagree": "gaedil", "argument": "gidael",
	"arise - become apparent": "Zahar", "arise - get up": "nahaD", "arithmetic": "hisaeb",
	"arm": "ziraeA", "arm wrestling": "rist", "armed": "musallah", "army": "geesh",
	"army officer": "ZubaaT geesh", "around - surrounding": "hawluh", "go around": "daar",
	"look around": "'itfarrag", "arrest": ["'abaD Aala", "misik"], "arrested": "'itmasak",
	"arrival": "wuSool", "arrive": "waSal", "arrogance": ["takabbur", "Aagrafa", "taAgruf"], 
	"arrogant": ["mutakabbir", "mutaAgrif"], "art": "fann", "art college": "finoon gameela",
	"artery": "shuryaen", "article": "band", "artifical": "SinaaAi", "artist": "fannaen",
	"artistic": "fanni", "as - like": "zayi", "as if": "Aala 'inn", "as soon as": "'awwil ma", 
	"as soon as possible": "fi 'asraA wa't", "as such - exactly": "biilZabT",
	"as well": "kamaen", "ascend": "TiliA", "ashamed (adj)": "maksoof", "(be) ashamed": "'istihi",
	"ashtray": "Taffaaya", "Asia": "asya", "aside": "ganbi", "ask - question": "s'aal",
	"ask (for)": "Talab", "ask for permission": "ist'azin", "asking for help": "'istaAaen",
	"asleep": "naeyim", "asleep - fall asleep": "niAis", "assemble - something": "gammaA",
	"assemble - people": "tagammaA", "assembly - meeting": "igtimaeA", "asshole": "'ahbal", 
	"assign": "haddid", "assignment": "muhimmma", "assist": "saeAid", "assistance": "musaeAid",
	"assorted": "mishakkil", "assortment": "tashkeela", "assume": "'iftaraD", "assumption": "'iftaraD",
	"assurance": "Damaan", "assure": ["ammin", "'akkid"], "assured (be)": "itTammin",
	"(be) astonished (vi inf)": "'istaGrab", "astonished (adj)": "mistaGrab", "(go) astray": "taeh", 
	"(gone) astray (adj)": "taeyih", "astronomy": "Ailm ilfalak", "at - place": ["Aand", "fi"],
	 "at - time": "fi", "at all": "Kaalis", "at first": "fi il'awwil", "at once - immediately": "haelan",
	 "at the same time": "fi nafs wa't", "at that time": "fi ilwa't da", "atheist": "kaefir",
	 "athlete": "riyaaDi", "atmosphere - weather": "gaww", "atmosphere - mood": "nifs",
	 "atom": "zarra", "atomic": "zarri", "attach (v inf)": "shabak", "attached (adj)": "mashbook",
	 "attached - emotionally (adj)": "mitAalla bi", "attack (n s)": "hugoom", 
	 "attack (v inf)": ["haegim", "'itAadda", "ithaggim"], "(be) attacked (v inf)": "ithaegim", 
	 "attempt (n s)": ["muhawla", "tagraba"], "attempt (v inf)": ["haewil", "garrab"],
	 "attend": "haDar", "attendance": "huDoor", "(pay) attention": ["Kalli baelak", "Kud baelak"],
	 "attention (n s)": ["ihitmaem", "intibaeh"], "attitude": "taSarrafaat", "attract (v inf)": "gazab",
	 "attracted (adj)": "magzoob", "(be) attracted - emotionally": "itgazab", 
	 "(be) attracted - mutually": "ingazab", "attraction - emotional": "gaezibiyya",
	 "attractive": "gazzaeb", "attractiveness": "gaeziba", "aubergine": "bitingaen",
	 "audacious": "garee'", "audacity": "gar'aa", "audience - listeners": "mustamiA",
	 "audience - spectators": "mutafarrigeen", "August": "'aGusTus", "aunt - address": "TanT",
	 "aunt - father's side": "Aamma", "aunt - mother's side": "Kaela", "Austrilia": "'usturalya",
	 "author": "kaetib", "authorised (adj)": "m'azoon", "authority": "sulTa", "authorize": "wakkil",
	 "autistic": "mutawahhid", "automatic": "'utoomateeki", "automatically": "'utoomateek",
	 "autumn": "ilKareef", "available - things only": "'itwaffar", "available - accessible, resources": "mitwaffar",
	 "available - present": "mawgood", "avarice": "buKl", "avaricious": "baKeel",
	 "avenge (v inf)": "'intaQam", "average (n s)": "mutawassiT", "aviation": "Tayaraan",
	 "avocado": "'avookadw", "avoid": "'ibaAd", "await": "'istanna", "aware (of)": "Aaerif",
	 "away - not available": "mish mawgood", "away (from)": "baAeeed Aan", "away - distant": "baAeed",
	 "awesome": "gaehid", "awful": ["shaneeA", "faZeeA"], "awkward - embarassing": "muhrig", 
	 "awkward - uncooperative": "SaAb", "awkward - clumsy": "laKmah", "awkward - clumsy or socially": "midahwil",}  

	return dict_a


def b_dict():
	dict_b = {"baby": ["beebi", "Tifl"], "back - behind": "wara", "back - body": "Dahr", 
	"backpack": "shanTit Dahr", "bad": ["wihish", "sayyi'"], "bad hair": "shaAr 'akrat",
	"badly (adv)": "bishakl sayyi'", "bag": ["kees", "shanTa"], "bake": "Kabaz",
	"baked": "maKbooz", "baker": "Kabbaez", "bakery": "furn", "baking": "Kabz",
	"balance - scale": "meezaen", "balcony": "balkoona", "bald": "'a'raA", "ball": "koora",
	"balloon": "balloona", "banana": "mooz", "bandage": "shaesh", "bang - knock": "KabbaT",
	"bank": "bank", "banker": "banki", "banking": "bankiyya", "bankrupt": "mifallis",
	"bar - place to drink": "baar", "bar - pub": "Kammaara", "bar - metal": "seeK",
	"barbecue": "shawi", "barbecued": "mashwi", "barber": "hallae'", "bare - naked": "Airyaen",
	"bare - empty": "faaDi", "barely": "yadoob", "bargain": "faaSil", "bargaining": "fiSaal",
	"basement": "badroom", "basic": "'asaesi", "basically": "'asaesan", "basics": "QawaeAid",
	"basil": "reehaen", "basis": "'asaes", "basketball": "korrit salla", "basketball net": "salla",
	"bass": "samak 'aross", "bastard": "'ibn haraam", "bat": ["Kuffaesh", "wiTwaaT"],
	"bath": "baneew", "bathe": "'istahamma", "bathing suit": "mayooh", "bathrobe": "roob",
	"bathroom": "hammaem", "bathtub": "baneew", "battery": "baTTaariyya", "bay leaf": "wara' lawra",
	"be": "kaen", "be quiet!": "'iskut", "bean": "fool", "green bean": "faSoolya KaDra", 
	"bear - animal": "dibb", "bear - endure": "'istahmil", "bear - carry": "shael",
	"beard": "za'n", "beast - evil": "wahsh", "beast - animal": "biheema", 
	"beat - hit": "Darab", "beat - in a game": "saba'", "beating": "Darb", "beautiful": "gameel",
	"beauty": "gamael", "because": ["li'in", "Aalashaen"], "because of": ["min", "bisabab"], 
	"become": "ba'a", "become - suddenly": 'istagadd', "bed": "sireer", "bedroom": "'UooDit noom", 
	"bee": "nahl", "beer": "beera", "beetroot": "bangar", "before": ["'abl", "'abl ma"], 
	"before - place": "uddaem", "beg - for money": "shahat", "beg - plead": "'itragga", 
	"beggar": "shahhaet", "begin": "'ibtada", "beginner": "mubtad'", 
	"beginning": ["bidaeya", "'ibtida'", "il'awwil", "'awwil"], "behave": "'itSarraf", 
	"behaviour": "taSarruf", "behind": "wara", "beige": "beej", "being": "ka'n",
	"Beirut": "bayroot", "Belgium": "bilgeeka", "belief": "AaQiyda", "believable": "maA'ool",
	"believe": "Sadda'", "believe (in) - religion": "'emin bi", "believing": "miSadda'", 
	"bell": "garas", "bell pepper": "filfil roomi", "pot belly": "kirsh", "belly": "baTn",
	"belly button": "surra", "belly dance": "ra'S baladi", 
	"belly dancer": ["Aalma", "raa'aSa baladi"], "belong": "bitaeA", "belongings": "bitooA",
	"beloved": "mahboob", "below": "taht", "belt": "hizaem", "bench": "binsh", 
	"beneficial": "mufeed", "benefit": ["istafaed", "faed"], "benefit - advantage": "fayda", 
	"beside": "ganb", "besides - other than": "Geer", "best": "'ahsan", "bet": "rahaan",
	"betray": "Kaen", "betrayal": "Kiyaena", "better": ["'ahsan min", "ahsan"], 
	"(you had) better...or...": "lahsan", "betting": "rahaan", "between": "been",
	"beverage": "mashroob", "beyond": "'abAad", "bias": "tahayyiz", "bible": "ilkitaeb ilmuQaddas",
	"bicycle": ["Aagala", "biskeelitta"], "big": "kibeer", "bigger": "'akbar", 
	"bike": "mootooseekl", "bill": "fatoora", "billion": "bilyoon", "biological": "hayawi",
	"biology": "Ailm il'ahy'a", "bird": "Teer", "bird - attractive woman": "muzza",
	"(give) birth (vi inf)": "Kallif", "birth (noun s)": "wilaeda", 
	"birth certificate": "shihaedit meelaed", "birthday": "Aeed meelaed", 
	"birthday party": "haflit Aeed meelaed", "biscuit": "baskaweet", "bishop": "muTraan",
	"bit": "hitta", "bitch - spiteful woman": ["kalba", "wisKa"], "bitch - complain": "shaka", 
	"bite - insect": "'arS", "bite - food": "AaDD", "bite - food": "lu'ma", 
	"bite - sting": "'araS", "bitter": "murr", "black": "'iswid", "black magic": "Aamal",
	"black-eyed peas": "loobya", "blackhead": "roos sooda", "blacksmith": "haddead",
	"blame": ["Aaetib", "laem Aala"], "blamed": "mitlaem", "blaming": "laeyim", 
	"blank": "faaDi", "blanket": "baTTaaniyya", "bleed": "nazaf", "blender": "KallaaT",
	"bless": "baerik", "blessed": "mubaarak", "blessing": "baraka", "blind": "'aAma",
	"blindfold": "Gamma", "blink": "Gamaz", "blister": "har'", "block  off - completely": "sadd",
	"blockage": "sadda", "blocked": "masdood", "blocked up": "'itsadd", "blocking": "sadd",
	"blonde": "'ash'ar", "blood": "damm", "blood pressure": "DaGT ildamm", "bloom": "ward",
	"blossom": "zahhar", "blouse": "bilooza", "blow - strike": "KabTa", "blow - with mouth": "nafaK",
	"blow dry": "seeshwaar", "blow out - a candle": "Tafa", "blowing": "nafK",
	"navy blue": "kuhli", "pale blue": "labani", "blue": "'azra'", "dark blue": "kuhli",
	"blunt": "thilim", "boast": "'iftaKar", "boasting": "faKr", "boat": "markib",
	"boatman": "marakbi", "body": "gism", "boil - cook": "sala'", "boil - water": "Gala",
	"boiled - food": "masloo'", "boiled": "maGli", "boiled water": "mayyah maGliyya",
	"boiler": "saKKaen", "boiling": "Galayaen", "bold": "garee'", "bond": "rubaaT", "bone": "Aadm",
	"boob": "bizz", "book": "kitaeb", "bookkeeper": "muhaesib", "bookshop": "maktaba",
	"boost": "zawwid", "boot": "boot", "boot of car": "shanTa", "(become) bored": ["mall", "zihi"],
	"boredom": "malal", "boring": "mumill", "(be) born (vi inf)": "'itwalad", 
	"born (part)": "mawlood", "borrow": "'istilif", "borrowing": "salaf", 
	"boss": ["ra'ees", "mudeer"], "both": "il'ithneen", "bother": "Daeyi'",
	"bottle": "'izaeza", "bottom": "tahtaeni", "serving bowl": "sulTaniyya", 
	"box": ["kartoona", "Ailba"], "boxing": "mulakma", "boy": "walad", "boyfriend": "Saahib",
	"bra": "sutiyaen", "bracelet": "'iswira", "brag": "iftaKar", "braid": "Dafeera", 
	"brain": "muKK", "brake (n s)": "faraamil", "brake (v inf)": "farmil",
	"brake cable (n s)": "teel faraamil", "brake pad (n s)": "waseadil faraamil",
	"brave (adj)": ["shugaeA", "garee'"], "be brave (vi inf)": "'itshaggaA", "bravery": "gar'aa",
	"break": "itkasar / kassar", "break - rest": ["'istiraaha / istirayih", "fusha"],
	"break - law": "Kaelif", "break down - stop working": "wi'if", "break down - nervous": "'inhaar",
	"break fast": "'ifTaar", "breaking": "kasr", "breast": ["bizz", "Sidr"], "breath": "nafKa",
	"breathe": "'itnaffis", "breeding - reproduction": "tirbaya", "breeze": "niseem",
	"brethren - very close friends": "'aKwaen", "bribe (n s)": "rashwa", "bribe (v inf)": "rasha",
	"bride": "Aaroosa", "bride and groom": "Aarees wa Aaroosa", "bridegroom": "Aarees",
	"bridge": "kubri", "brief": "muKtaSar", "briefcase": "shanTa", "briefly": "bi'iKtaSaar",
	"bright - intelligent": ["nabeeh", "zaki"], "bright - light colors": "saaTiA", 
	"brilliant": "shaaTir", "bring": ["haet", "gaeb"], "bring back": "raggaA", 
	"bring out": "TallaA", "bring up - raise a child": "rabba", "bring down": "nazzil", 
	"bring up": "TallaA", "Britain": "briTanya", "British": "breeTaani", "broccoli": "burookuli",
	"broke": "mifallis", "broken - damaged": "maksoor", "broken in pieces": "midashdish", 
	"broom": "ma'ashsha", "brother": "'aKK", "brown": "bunni", "brown skinned": "'asmar",
	"bruise": "kadma", "brunette": "'asmar", "brush": "fursha", "to brush": "sarrah", 
	"bubble": "balloona", "bucket": "gardal", "budget": "meezaeniyaa", "buffalo": "gamoos",
	"buffet": "booffeeh", "bug": "hashara", "(to) build (v inf)": "bana", 
	"builder": "banna", "building": ["Aimaara", "mabna"], "construction building": "bina",
	"built": "'itbanna", "bulb": "lumba", "bull": "thoor", "bullet": "ruSaaS", 
	"bully (n s)": "mushaekis", "bully (v inf)": "shaekis", "bump (v inf)": ["Sadam", "KabaT"],
	"bump - collision": "Sadma", "bump in road": "maTab", "(be a) burden (v inf)": "barshaT", 
	"bureau - office": "maktab", "burgundy": "nibeeti", "burial": "dafn", 
	"burial site": "madfan", "burn something": ["hara'", "wallaA"], "burn - food": "shaaT",
	"burn - by itself": "'ithara", "burn - scorch": "lasaA", "burnt out": "'ithara", 
	"bury": "dafan", "bus": "'utoobees", "bus terminal": "'eKir ilKaTT", "bush": "shagar",
	"business": "shuGl", "businessman": "ragul 'aAmael", "busy": "mashGool", 
	"but": ["laekin", "bass", "bil", "maAa zalik"], "butcher": "gazzaar", "butchery": "gizzaara",
	"butter": "zibda", "butterfly": "faraasha", "button": "zuraar", "buy": "'ishtara", 
	"buyer": "mushtari", "buying": "shira'", "by - next to": "ganb"}

	return dict_b


def c_dict():
	dict_c = {"cab - taxi": "taksi", "cabbage": "kurunb", "cabin": "kabeena",
	"cabinet": "doolaeb", "electric cable": "kabl", "brake cable": "teel faraamil",
	"cactus": "Sabbaar", "cafe": "'ahwa", "cafeteria": "kafeeteeria", "cage": "'afas", 
	"Cairo": "ilQaahira", "cake": "keek", "calculate": "hasab", "calculation": "hisaeb",
	"calculator": "'ela hasba", "calendar": ["taQweem", "nateega"], "calf muscle": "simmaena",
	"call on phone (v inf)": "kallim", "call - shout someone's name": "nada", 
	"calm down": "'ihda", "calm (adj)": "haedi", "calorie": "saAr haraeri", 
	"camel": "gamal", "camera": "kameera", "camp (n s)": "muAskar", "camp (v inf)": "Aaskar",
	"can - able": ["'idir", "mumkin", "Airif"], "can - could": "mumkin", "Canada": "kanada",
	"cancel": "laGa", "cancellation": "ilGa'", "cancelled": "'itlaGa", "cancer": "saraTaan",
	"candle": "shamA", "candlestick": "shamAidaen", "candy": "hilawa", 
	"canned food": "muAallabaet", "cannot": ["ma'idirsh", "mish mumkin", "mish 'aedir", "mayinfaAsh"],
	"cantaloupe": "kantaloob", "cap - hat": "Taa'iyya", "cap - bottle": "GaTa",
	"capability": "'adr", "capable": "aedir", "capacity - space": "siAa", 
	"capacity - ability": "Qudra", "capital city": "AaaSima", "capital letter": "harf kibeer",
	"captain": "kabtin", "capture": "'abaD", "captured": "'asar", "car": "Aarabiya",
	"carbohydrates": "karbooheedraat", "carbon": "karboon", "(playing) card": "kutsheena",
	"card": "kart", "cardboard": "kartoon", "care - for sick person": "riAeya", 
	"care - be concerned": "'aAtana", "care about": "'ihtamm", "care": ["raAa", "'ihtamm", "haafiZ"],
	"care - concern": "Aanaeya", "be careful": "harraS", "carefully": "bihazzar", "careless": "muhmil", 
	"carer": "raaAi", "caring": "muhtamm", "carpenter": "naggaar", "carpet": "siggaeda", 
	"(be) carried away": "'itgaraf", "carrot": "gazar", "carry": ["shael", "hamal"],
	"exp - carry on": "zayi ma 'inta (lit. as you are)", "carry out": "'agra", 
	"carrying": "shaeyil", "cart": "Aarabiyya", "cartoon": "kartoon", "case - instance": "haela",
	"case - suitcase": "shanTa", "cashier": "Sarraff", "cast - throw": "rama", 
	"cat": "'uTTa", "catch - capture": "misik", "catch - a disease": "'itAada",
	"catch - a train": "lihi'", "catch up (with)": "lihi'", "catching": "mask",
	"catering": "tazweed", "cattle": "biheema", "cauliflower": "'arnabeeT", 
	"cause - make something happen (n s)": ["sabab", "'agl", "'aSl"], "cause (v inf)": "sabbib",
	"cautious": "hazar", "cease": "KiliS", "cedar": "'arz", "ceiling": "sa'f",
	"celebrate": "'ihtafal", "celebration": ["'ihtifael", "Aeed"], "celery": "karafs", 
	"celery salt": "budrit karafs", "cell - prison": "zinzaena", "cell - organism": "Kaliyya",
	"cellar": "badroom", "cement": "'asmant", "cemetery": "madfan", "centimetre": "santeemitr",
	"central": "markazi", "center": "markaz", "cenutry": "Qarn", "cereal": "huboob",
	"ceremony": "hafla", "certain - confirmed": "mw'akkad", "certain - sure": "mut'aakkid",
	"certainly": "akeed", "certainty": "t'akeed", "certificate": "shahaeda", 
	"chain - jewlery": "silsila", "chair": "kursi", "chairman": "ra'ees", 
	"chalk": "Tabasheer", "challenge (n)": "tahaddi", "challenge (v inf)": "tahadda",
	"chameleon": "hirba'", "champion": "baTal", "championship": "buToola", 
	"(by) chance (adv)": "biilSudfa", "chance - opportunity": "furSa", 
	"change - modification": "taGGayir", "change - one thing for another": "Gayyar",
	"change - small change (money)": "fakka", "change - money": "fakk", 
	"changeable": "mutaQallib", "changed": "'itGayyar", "changing": "mitGayyar", 
	"channel": "Qanaet", "chaos": "fawDa", "chapel": "kineesa", "charcoal": "fahm",
	"charge - fee": "tazkara", "charge - money": "haesib", 
	"charge - legal indictment": ["tuhma", "'ittihaem"], "(be) charged": "'ittaham",
	"charger": "shaehin", "charm (n)": "Zurf", "charm (v inf)": "gazab", 
	"charming": "Zareef", "chase (v inf)": "Tarrid", "chase - a woman to seduce her": "nammar",
	"chat (n s)": ["hadeeth", "dardasha"], "chat (v inf)": ["tharthar", "dardish"],
	"(become) cheap (vi inf)": "riKis", "cheap (adj)": "riKeeS", "cheat": ["Gashsh", "Kaen"],
	"cheating": "Kiyaena", "check - examine": "kashaf Aala", "check - look at": "shaef",
	"check - review": "tammim Aala", "check - bill": "fatoora", 
	"checkup - medical": "kashf", "cheek": "Kadd", "cheer (v inf)": "hataf", 
	"cheese": "gibna", "cheetah": "fahd ilnaQaT", "chemical": "madda keemya'yya",
	"chemistry": "keemya", "cheque": "sheek", "cherry": "kireez", "chess": "shaTarang",
	"chest": "Sidr", "chest - box": "Sandoo'", "chew": "maDaG", "chewing gum": "libaen",
	"chick - baby bird": "katkoot", "chick - attactive woman": "muzza", 
	"chick pea": "hummuS", "chicken": "farKa", "chief": "ra'ees", 
	"child": ["Tifl", "walad", "Aayil"], "childhood": "Tufoola", "childish": "Aayil", 
	"chill": "sa'aA", "chill out": "'ihd'a", "chilli": "shaTTa", "chilly": "bard", 
	"chin": "za'n", "China": "ilSeen", "Chinese": "Seeni", 
	"chip - french fries": "baTaaTis mihammara", "chlorine": "kuloor", 
	"chocolate": "shookoolaata", "choice": "'iKtiyaar", "choke": "shiri'", 
	"choking - something stuck in throat": "shar'aen", "choking - drink": "shar'aen",
	"choking - food": "zawraan", "choose": ["'iKtaar", "na'a"], "chop": "KarraT",
	"christian": "miseehi", "christian calendar": "meelaadiya (lit. birth (or Christ)",
	"christmas": "Aiyd ilmeelaed", "church": "kineesa", "cigarette": "seegaara",
	"cigarette butt": "Au'b sigaara", "cilantro": "kuzbara", "cinema": "seenima",
	"cinnamon": "'irfa", "(social) circle": "hala'a", "circle - shape": ["dayra", "taara"],
	"circle - go around": "daar - yidoor", "circle - roundabout": "Seeniyya",
	"circuit - circular path": "dawaraan", "circuit - electrical": "dawra", 
	"circumstance": ["Zarf", "hael"], "citizen": "muwaaTin", "city": "madeena",
	"civilian": "madani", "claim (n s)": "shakwa", "claim (v inf)": ["'iddaAa", "'ishtaka",],
	"clash - argue": "'isTadam", "class - grade": "daraga", "class - school": ["dars", "faSl"],
	"classic": "klasseeki", "classical": "klasseeki", "classroom": "faSl", 
	"(become) clean (vi inf)": "niDif", "clean (adj)": "niDeef", "cleaned": "naDDaf",
	"cleaning": "tanDeef", "clear - understanble explanation": ["waaDih", "Zaahir", "Saafi"],
	"clear (weather)": "ilgaww Saafi", "clear - transparent": "shaffaef", 
	"(be clear)": "baen", "(make) clear": "bayyin", "evident": "baeyin", 
	"clearly": "biwuDooh", "clench - teeth": "gazz", "clench - fist": "Damm", 
	"clever": ["shaaTir", "naaSih", "zaki"], "climate - environment": ["bee'a", "gaww"],
	"climate - weather": "munaeK", "climb": "TiliA", "cling": "tamaesak", 
	"hair clip": "tooka", "clock": "saeAa", "clock - alarm clock": "minabbih", 
	"close - near": "'urayib", "close (v inf)": "'afal", "close (one's eyes)": "GammaD",
	"(get) close (to)": "'arrab", "closed": ["ma'fool", "'aefil"], "(be) closed": "'if'afal",
	"closer": "'a'rab", "closet": "doolaeb", "clot": "galTa", "clothes": ["libs", "hudoom", "malaebis"],
	"clothing": "hudoom", "cloud": ["Geem", "sahaeb"], "(be) cloudy": "ildinya Gayamit",
	"cloudy (adj)": "miGayyima", "clown": "bahlawean", "club - social": "naedi",
	"(give a) clue (v inf)": "lammah li", "clue (n s)": "dalleel", 
	"clumsy": ["mitkaAbil", "midahwil", "laKmah"], "clutch": "dibriyaej", "coach": "mudarrib",
	"coat": "balTw", "cocaine": "kookayyin", "cock - male hen": "deek", "cock - male organ": "zib",
	"cococa": "kakaew", "coconut": "gooz hind", "code - pass": ["shafra", "ramz"],
	"cofee": "'ahwa", "coffee shop": "'ahwa", "coffin": "taboot", "coincidence": "Sudfa",
	"(get) cold (vi inf)": ["birid", "si'iA"], "(ice) cold (adj)": ["sae'iA", "mitallig"], 
	"(feeling) cold (part)": "bardaen", "cold drink": "sae'iA", "collapse (v inf)": "'inhaar", 
	"collapse (n s)": "'inhiyaar", "collarbone": "tur'wa", "colleague": "zameel", 
	"collect": ["lamm", "gammaA"], "college": "kulliyya", "collide": "'itSaadim", 
	"collision": "taSaadum", "color (n s)": "loon", "color (v inf)": "lawwin", 
	"colored (adj)": "milawwin", "colorful": "mulawwan", "column": "Aamood", 
	"comb (n s)": "mishT", "comb hair (v inf)": "sarrah", "combination": ["gamA", "'ittahaed", "magmooAa"],
	"combine": "wahhid", "combined": "muKtalaT", "come": ["gih", "taAaela"],
	"come back": "rigiA", "come before": "saba'", "come in": ["daKal", "Kushsh"],
	"come on": "Aaekis", "come on! - let's go": "yalla beena", "come on! - really!": "ya salaem",
	"come  out": "Karag", "come up": "TiliA", "comedy": "koomeedya", "comfort (n s)": "'irtiyaeh",
	"comfortable - furniture": "mureeh", "comfortable - relaxed": ["mirtaeh", "mistarayah"],
	"coming": "gayi", "command (v inf)": "'emar - yu'emur"}


	return dict_c


def d_dict():

	dict_d = {"dad": "baeba", "dagger": "Kangar", "daily": "yoomyan", "dairy": "labani",
	"dam": "sadd", "damage": "bawwaZ", "damaged": ["baaZ", "'itKabaT"], "damn": "liAan",
	"dance (n s)": "ra'Sa", "dance (v inf)": "ra'aS - yur'uS", "dancer": "raQQaS", 
	"dancing": "ra'S", "dandruff": "'ishrit shaAr", "danger": "KaTar", 
	"dangerous": "KaTeer", "dare - risk (v inf)": "gar' - yugrw'", 
	"daring" : "garee'", "(it is) dark (expr)": "ildinya Dalma", "dark - color": "Gaemi'",
	"dark - not light": "muZlim", "(get) dark (vi inf)": "Zalam", "dark meat": "wirk",
	"dark skinned": "'asmar", "darkness": ["Dalma", "Zalaam"], "darling": "habeeb", 
	"data": "maAlooma", "database": "QaaAidit ilbayanaet", "date - appointment": "'agal",
	"date - calendar": "tareeK", "date - fruit": "tamr", "dating": "miSahhib", 
	"daughter": "bint", "dawn": "fagr", "day - 24 hours": "yoom", "day - not night": "nahaar",
	"day off": "'agaeza", "daydream": "sarah", "daydreamer": "sarraah", "daydreaming": "sarhaen",
	"days": "ilyoomeen dool", "daytime": "nahaar", "dead": "mayyit", "deadline": "'eKir maAaed",
	"deaf": ["'aTrash", "'aSamm"], "(make a) deal": "'ittafa'", "deal with - problem": "'itSarraf",
	"deal with - manage": "Aaemil", "deal - trade (n s)": "tabaedul", "deal - trade (v inf)": "taegir",
	"dealer - trader": "taegir", "dealer - eg drugs": "deeleer", "dealing - trading": "tabaedul",
	"death (n s)": "wafaet", "(in) debt (adj)": "madyoon", "debt (n s)": "deen", 
	"(fall into) debt": "'itdaen", "debtor": "madeen", "decade": "Aashar sineen", "deceitful": "KiddaeA",
	"deceitful person": "'awanTagi", "deceieve": ["waham", "Kamm"], "December": "deesimbir",
	"decent - respectable": "muhtaram", "decide": ["Qarrar", "gazam", "hasam"], "decision": "Qaraar",
	"deck of cards": "kutsheena", "declare": "'aAlan", "decline": "'inKafaaD",
	"decline - deteriorate": "nizil", "decor": "deekoor", "decorate": "zayyin", "decoration": "zeena",
	"decrease (v inf)": ["'all", 'na"aS'], "decrease (n s)": "ta'leel", "deed (n s)": "Aamal", 
	"(bad) deed": "diniyya", "deep purple": "bitingaeni", "deep water": "Garee'",
	"deer": "Gazael", "default": "'iftiraaDi", "defeat - in fight or game or argument (n s)": "hazeema",
	"defeat - in fight or in game (v inf)": "hazam", "defeat - in game (v inf)": "Galab", 
	"defer - postpone": "'aggil", "definite": "mw'akkad", "definitely": ["hatman", "expr: la mahaela"],
	"definition": "taAreef", "defraud": "'itlaeAib", "degree - qualification": ["dibloom", "shahaeda"],
	"degree - temperature": "dagara", "deity": "'ellah", "delay (v inf)": "'aKKar",
	"delayed": "mit'aKKar", "delete": "hazaf", "deliberately": "bitaAmmud", "delicate": "ra'ee'", 
	"delicious": "lazeez", "delight (v inf)": ["nawwar", "'abhag"], "deliver": 'waSSal', 
	"delivery": "tawSeel", "democracy": "deemuQraaTiyya", "democrat": "deemu'raaTi",
	"democractic": "deemu'raaTi", "demolish": "hadd", "demon": "Aafreet", 
	"demonstrate - explain": ["sharah", "waDDah"], "demonstration - show something": "sharh", 
	"denial": "guhood", "dentist": ["duktoor 'asnaen", "Tabeeb 'asnaen"], "deny": ["nafa", "nakar", "gahad", "'ankar"], 
	"depart": "mishi", "departure": "safar", "depend - conditional": ["'iAtamad Aala", "'aAtimaed"], 
	"depend - rely on": ["'ittakal Aala", "'aAtamid"], "depending": "hasab", "depressed": "mukta'ib", 
	"depression": "'iki'aeb", "dermatologist": "duktoor 'amraaD gildiyya", "descend": "nizil", 
	"describe": "waSaf", "description": "waSf", "desert": "Sahara'", "desert - leave": "hagar", 
	"deserve": ["'istaehil", 'istaha"'], "deserving": "tistaehil", "design - technical drawing": "rasm fanni",
	"design (v inf)": "Sammim", "designer": "muSammim", "desirable": "marGoob", "desire - possession": "nifsi fi", 
	"desire - lust": "raGab / raGba", "desk - office": "maktab", "despair": "y'aas", "despaired": "mayw's", 
	"despairing": "y'as", "desperate": ["y'as", "faaQid il'amal"], "desperately": "biy'as", 
	"despite - circumstances": ["biilraGm", "Aala ilraGm min", "raGm"], "dessert": "hilw",
	"desserts - what someone deserves": "gaza'", "destination": "'ittigaeh", "destiny": "Qadar",
	"destroy": ["Karrab", "dammar", "daGdaG", "Aadam"], "(be) destroyed": ["'atlaf", "itdammar"], 
	"destroyer": "mudammira", "destruction": "'itlaef", "destructive": "mutlif", "detail": "tafSeel",
	"detailed": "mufaSSal", "detect": "'iktishif", "deteriorate": "nizil", "deteriorated": "sayyi'", 
	"deterioration": "talaf", "determination": "Azm", "determine": ["faSSal fi", "'iktishif"], "determined": "muSammim",
	"develop - skill": ["namma", "Tawwar"], "development - progress": "taTawwur", "device": "gihaez", "devil": "sheeTaan",
	"devilish": "sheeTaani", "devious person - slippery": "expr: matArafsh timsikuh", "devious (adj)": "waaTi",
	"devise": "KaTTaT", "devote": "'iltazam", "devotion": "'iltizaem", "diabetes": "maraD ilsukkar",
	"diagnosis": "tashKeeS", "diagram": "rasm fanni", "dial": "Darab", "dialect": "lahga", "dialogue": "hiwaar",
	"diamond": "'almaaZ", "diarrhea": "'ishael", "dick": "zib", "dictionary": "Qamoos", "die": "maet", 
	"diesel": "deezil", "diet": "reejeem", "differ": "'iKtalaf", "difference (n s)": ["far'", "'iKtilaef"],
	"(make a) difference (v inf)": "farra'", "different (adj)": "muKtalif", 
	"different - other than / different to": "Geer", "differently": "bi'iKtilaaf", 
	"difficult - not easy / uncooperative": "SaAb", "difficult to get rid of": "Gitit", "difficulty": "SuAooba",
	"digest": "haDam", "digital": "raQami", "dignity": "karaama", "diligence": "'igtihaed", "dine": "'itAashsha",
	"diner": "maTAam", "dining room": "'uooDit sufra", "dinner": "Aasha'", "diploma": ["dibloom", "shahaeda"],
	"diplomat": "dibloomaesi", "direct (adj)": "mubaeshir", "direction": "'ittigaeh", "directly": "haelan", 
	"director - buisness": "mudeer", "dirt": "turaab", "dirty": "wisiK", "dirty (water)": "mayaat Sarf", 
	"(get) dirty": "'itwassaK", "disability": "Aa'Q", "disabled - person": "muAaaQ", "disadvantage": "Aa'Q",
	"disagree (with)": "'iKtalaf", "disagree": "'iAtaraD", "disagreement": "'iKtilaef", "disappear": "'iKtafa",
	"disassembled": "mafkook", "disassembly": "fakk", "disaster": ["kartha", "muSeeba", "balwa"], "disc": "disk",
	"disciple": "tilmeez", "discipline - subject": "QawaeAid", "discipline - punish": "AaaQib", 
	"discipline - strict": "t'adeeb", "discipline - training": "t'adeeb", "discipline - punishment": "t'adeeb",
	"discourage": "sabbit", "discover": ["kashaf", "'iktishif"], "discovery": "'iktishaef", 
	"discuss": ["baehith", "nae'ish"], "discussion": ["muna'sha", "mubaehatha", "munaZra", "muhaedatha", "niQaash"],
	"disease": "maraD", "disease - catch a disease": ["'itAada", "gih"], "disgust": "'irif", 
	"disguisted (part)": "'arfaan", "(be) disguisted": "'it'araf", "disgusting": "mu'rif", "dish - tableware": "Taba'",
	"dish - meal": "'akla", "dish washer": "Gassaelit 'aTbaa'", "dishonest": "nadl", "disk": "deesk", "dislike": "mahabbish",
	"dismantle": "fakk", "dismiss": "Tarad", "disobey": "'iKtalif", "disorganization": "fawDa", "distance": "'abaAaed",
	"distant": "baAeed", "distinct - clear": "baeyin", "distinguish": "mayyiz", "distract": "shattit", 
	"distracted": "sarhaen", "distress (n)": "ziAl", "distress (v inf)": "zaAAal", "distressed": "zaAlaen", 
	"disturb": "'azAag", "disturbance": "'izaAaeg", "(be) disturbed": ["'inzaAag", "'itDaeyi'"], "dizziness": "dooKa",
	"(become) dizzy": "daeK", "(make so) dizzy": "dawwaK", "dizzy (adj)": "daeyiK", "do - action": "Aamal", 
	"do - question --> eg: do you know...": "hall", "do me a favour": "min faDlak", "do you mind?": "Aandak maeniA?",
	"doctor": ["Tabeeb", "duktoor"], "doctorate": "duktooraat", "doctrine - relgious": "AaQiyda", 
	"doctrine - teaching": "taAaleem", "document": "wara'a", "dog": "kalb", "dogma": "AaQiyda", 
	"doing": ["(n s) Aamal", "(part) Aaemil"], "doll": "Aaroosa", "dollar": "doolaar", "dolphin": "darfeel", 
	"dominant": "musayTir", "dominate": "sayTar", "don't": "mish", "dont bother": "balaesh", "dont": ["balaesh", "bass"],
	"done": "'itAamal", "donkey": "humaar", "door": ["baeb", "bawwaeba"], "doorbell": "garas baeb", "doorman": "bawwaeb",
	"double - number, quantity": "muzdawag", "doubt": "shakk", "without doubt": "min Geer shakk", "doubtful": "mubham", 
	"doubting": "shaekik", "dove": "hamama", "down": "taht", "download": "hammil", "downstairs": "taht", 
	"dozen": "'itnaeshar", "drag": ["sahab", "garr", "shadd"], "draw - sports": "taAedul",
	"draw - a picture": "rasam", "draw - pull": "sahab", "draw near (to)": "'arrab", "drawer": "durg", "drawing": "rasm",
	"drawing pin": "dabboos rasm", "dreadful": ["faZeeA", "raheeb"], "dream (n s)": "hilm", "dream (v inf)": "hilim",
	"dress - (n s)": "fustaen", "dress (vi inf)": "libis", "dressed": "laebis", "dresser": "doolaeb", "dressing": "libs",
	"dressing room": "'uooDit libs", "dried": "naeshif", "drink (n s)": "mashroob", "drink (v inf)": "shirib", 
	"drink - alcoholic": "Kamra", "drinking": "shurb", "drive (v inf)": "sae'", "drive - animals, insects away": "hishsh",
	"drive - people away": "Tarad", "drive (crazy)": "gannin", "driver": "sawwae'", "driver's license": "ruKSit siwae'a",
	"driving": "siwaa'a", "drop - fall (n s)": ["saQTa", "wa'Aa"], "drop - fall (vi inf)": "sa'aT", 
	"drop - of liquid": "nu'Ta", "drop - something": "wa'aA", "drowsy": "naAsaen", "dry": ["(adj) naeshif", "(v inf) nishif"],
	"(hair) dryer": "seeshwaar", "Dubai": "dubai", "duck": "baTT", "dude": "shabb", "dumb": "Gabi", 
	"(act) dumb - pretend to be stupid": "'istaGba", "duration": "mudda", "during": ["'athna'", "fi Kilael", "'athna' zalik"],
	"duty": "waegib"}

	return dict_d

def e_dict():

	dict_e = {"each": "kull", "each one": "kull waehid", "each other": "baAD", "eager": "mutashawwa'", "eagle": "nisr",
	"ear": "widn", "earlier": "min shuwaya", "early": "badri", "early morning expr": "EG expr wishsh ilSubh", "earn (v)": "kisib",
	"earner": "kisb", "earning": "kisb", "earrings - pair": "hala'", "earth": "'arD", "earthquake": "hazza 'arDiyya", 
	"ease (n)": "suhoola", "(with) ease (adv)": "bisuhoola", "easier": "'ashal", "easily": "bisuhoola", "east": "shar'",
	"easter": "Aiyd ilQiyaema", "easter monday": "Aiyd shamm ilnissem" ,"eastern": "shar'i", "easy (adj)": "sahl", "(make) easy (v inf)": "sahhil",
	"easygoing": "thi'eel", "eat": "kal", "eat breakfast": "ifTar", "eat dinner": "'itAashsha", "eat junk food": "ramram", 
	"eating": "'akl", "echo": "Sada", "(solar) eclipse": "kusoof", "(lunar) eclipse": "Kusoof", "economic": "'iQtiSaadi",
	"economical": "'iQtiSaadi", "economics": "'i'tiSaad", "economise": ["'i'taSad", "waffar"], "economy": "tawfeer", 
	"education (adj)": "mutaAallim", "(be) educated": "'eddib", "education": ["taAleem", "'adabiyya", "t'adeeb"], 
	"educational": ["tarbawi", "taAleemi"], "effect (n)": "t'atheer", "effect (v)": "naffiz", "effective": "baleeG", 
	"effectively": "Aala nahw fiAael", "effectiveness": "faeAiliyya", "efficiency": "faAaeiliyya", "efficient": "kuf'", 
	"effort (n s)": "mahgood", "(make every) effort (v inf)": "bazal guhduh", "(make an) effort (v inf)": "bazal",
	"egg": "beeD", "eggplant": "bitingaen", "egoistic": "'anaeni", "(Upper) Egypt": "ilSaAeed", "Egypt": "masr", 
	"Cairo and Alexandria (lower) Egypt": "ilwagh ilbahari", "Egyptain": "maSri", "eight": "tamanya", "eighteen": "tamantaashar",
	"eighth": "taemin", "one-eighth": "thumn", "eighty": "tamaneen", "either - I don't want it either": "kamaen", 
	"either - you can have either (of them)": "waehid min il'itneen", "elastic": "'astik", "elbow": "kooA", "elderly": "Aagooz",
	"elect": "'intaKab", "elected": "muntaKab", "election": "'intiKaeb", "electoral": "muntaKab", "electric": "kahrabaa'i",
	"electrical": "kahrabaa'i", "electrican": "kahrabaa'i", "electricity": "kahraba'", "electron": "'iliktroon",
	"electronic": "'iliktirooni", "elegant - elegance (n)": "skyaeka", "elegant (adj)": "sheek", "element - component": "AunSur",
	"elephant": "feel", "elevator": "'asanseer", "eleven": "hidaashar", "eleventh": "'ahad Aashar", "eloquence": "balaeGa",
	"eloquent": ["faSeeh", "baleeG"], "else (adj)": "walla", "else - other": "thaeni", "email": "'imeel", 
	"embarrass": ["kasaf", "'ahrag"], "(be) embarasssed (vi inf)": "'itharag", "embarassed (adj)": "maksoof", "embarassing": "muhrig",
	"embarassment": "kusoof", "embassy": "sifaara", "embrace (n)": ["baaT", "huDn"], "embrace (v inf)": "tashabbith", 
	"emerald": "zumurrud", "emerge": "Karag", "emergency": "Tar'", "Emirates": "il'imaraat", "emission": "TallaA", 
	"emotion": "'ihsaes", "emotional": "AaaTifi", "emphasis": ["tashdeed", "t'akeed"], "emphasise": "shaddid",
	"emphasize": "haddid", "employ (v inf)": ["waZZaf", "Aayyin"], "employed": "mitAyin", "employee": ["mustaKdam", "muwaZZaf"],
	"employer": "muwaZZif", "employment": "tawZeef", "emptiness": "faraaG", "(become) empty": "fiDi", "empty (adj)": "faaDI",
	"enable (v inf)": "makkin", "encourage": "shaggaA", "end - finish": "nihaeya", 
	"end": ["Kilis", "Kallas", "'intaha", "tamm", 'eKir'], "ending": "nihaeya", "endless": "la nihae'i", "endure - bear": "'istahmil",
	"enemy": "Adw", "energetic": "nusheeT", "energy": "hayawiyya", "engaged - man": "KaTab - yuKTub", "engaged - woman": "'itKaTabit - yitKiTib",
	"engagement": "KuTooba", "engagment gift": "shabka", "engagment ring": "dibla", "engine": "mootoor", "engineer": "muhandis",
	"engineering": "handasa", "England": "'ingiltira", "English": "'ingileezi", "enjoy": "'itmattaA", "enjoy (oneself)": "'inbasaT",
	"enjoyable": "mmumtiA", "enlarge": "wassaA", "enormous": "DaKm", "enough": "kifaeya", "(be) enough": "kaffa", 
	"enough!": ["KalaaS", "bass", "kifaeya"], "enter": ["Kushsh", "daKal - yudKul"], "entertain": "salla - yisalli", 
	"entertainer - in street": "haewi", "entertaining": "musalli", "entertainment": "tarfeeh", "enthusiasm": "hamaes", 
	"enthusiastic": ["mutahammis", "hammaesi"], "entire": ["kaemil", "kull", "tamm"], "entirely": "KaaliS", 
	"entrance - coming in": "duKool", "entrance - doorway": ["madKal", "baeb"], "entry": "duKool", "enumerate": "Aadd", 
	"envelope": "Zarf", "envious": "hashood", "environment": "bee'a", "environmental": "bee'i", "envy": "hasad",
	"epic": "malhami", "episode - TV": "musalsal", "equal (adj)": "mutasaewi", "(make) equal (v inf)": ["'itsawa", "Aaedil", "sawa"],
	"equal to": "'add", "equality": "musawaet", "equally": ["biiltisaewi", "tisaewi"], "equation": "muAadla",
	"equip": "zawwid", "equipment": "muAidaet", "equivalent": ["(n) yisaewi", "(adj) muwaezi"], "erase": "masah", 
	"eraser - blackboard": ["bashawra", "massaeha"], "eraser - rubber": "'asteeka", "errand": "mishwaar", "error": "GalTa",
	"escalator": "sillim", "escape": ["Karag", "hirib"], "especially": "KuSooSan", "essay": "maQaala", "essential": "Daroori",
	"essentially": "'aSlan", "establish": "'iktishif", "estimate (n s)": "mu'aysa", "estimate (v inf)": ["'addar", "thammin"],
	"estimated": "muQaddar", "eternal": "dae'im", "Europe": "'uooroobba", "European": "'uooroobbi", "evaluate": "Qayyim",
	"evaluation": "taQyim", "evasive": "hawwar", "even (adj)": "hatta", "even - level, smooth (adj)": "mitsaewi",
	"even though": "walaw", "evening (n s)": "masa'", "(in the) evening (adv)": "biileel", "event - incident": "hadath",
	"event - gathering": "munasba", "eventually": "'aKeeran", "ever - never": "'abadan", "ever - have you ever...": "Tool Aumrak",
	"ever - for ever": "liil'abad", "ever again": "baAd kida", "every": "kull", "every week": "kull 'usbooA", "every day": "kull yoom",
	"every so often": "kull shuwaya", "every time / every time that..": "kull ma", "every year": "kull sana", "everybody": "kull waehid",
	"everyday": "Aaedi", "everyone": ["ilkull", "kull ilnaes", "kull waehid"], "everything": "kull haega", 
	"everywhere": ["fi kul makaen", "fi makaen ma", "fi kull hitta"], "evil": ["sheeTaani", "wihish"], 
	"exact - accuracy": "maZbooT", "exact - fact": "Sahh", "exactly": ["biilZabT", "biiltamaem"], 
	"exaggerate": ["baeliG", "hawwil"], "exaggeration": ["mubalGa", "tahweel"], "exam": "'imtahaen", "examination - medical": "kashf",
	"examination - academic": "'imtahaen", "examine - evaluate": "'imtahan", "evaluate - medically": "kashaf", "examining": "kashf",
	"example": "mathal", "(for) example": "mathalan", "exceed": "tafawwaQ", "excel": ["'itfawwa'", "'imtaez"], "excellent": "mumtaez",
	"except": ["'illa", "maeAada", "Geer ma"], "exception": "'istithna'", "exceptional": "'istithnae'i", "excess": "kutr",
	"excessive": ["mubaeliG", "kutr"], "excite": ["'athaar", "hammis"], "(be) excited": "thaar", "excited (adj)": "mutahammis",
	"exciting": "mutheer", "exclude": "'istibaAid", "exclusion": "'istibaAaed", "excuse (onself) - depart": "ista'zin", 
	"excuse me": ["Aan 'iznak - to get past somebody", "bAad 'iznak - to stop somebody to ask for something", "law samaht"],
	"excuse me!": "maAlish", "(make) excuses": "'ithaggig", "execute - carry out": ["naffiz", "'agra"], "execute - person": "'aAdam",
	"execute - finish": ["'angaz", "naffiz"], "execution - implementation": "tanfeez", "execution - person": "'iAdaem",
	"exercise - physical": "tamreen", "exhalation": "zafeer", "exhausted - tired": ["taAbaen", "murhaQ", "halkaen", "hamdaen"],
	"exist": "kaen", "existence": "wugood", "existing": "mawgood", "exit": "Karag", "exiting": "Kuroog", "expand": "'itwassaA",
	"expansion": "tawsiyaA", "expect - outcome": "tawaQQaA", "expectation": "tawaQaA", "expected": "mutawa'aA", 
	"expecting (a baby)": "haemil", "expense": "maSroof", "(become) expensive": "Gili", "expensive": "Gaeli", "(more) expensive": "'aGla",
	"experience (n s)": ["Kibra", "tagriba"], "experience (v inf)": "garrab", "experienced": "Kabeer", "experiment (n s)": "tagruba",
	"experiment (v inf)": "garrab", "experimental": "tagreebi", "experimenter": "mugarrab", 
	"expert": ["hirafi", "Kabeer", "'el ilKibra", "mugarrab"], "expire": "'intaha", "expired": "mintihi", "explain": ["sharah", "fahhim"],
	"explanation": ["sharh", "tafseer"], "explicit - clear": "waaDih", "explicit - precise": "muhaddad", "exploration": "'iktishaef",
	"explore": "'istakshif", "explode": ["'infagar", "'itfar'aA"], "explosion": "'infigaar", "extend - renew": "gaddid", 
	"extend - make bigger": "'itTawwil", "extend - arm": "midd", "(be) extended": "'itgaddid", "extra": "ziyaeda", "eye": "Aeen",
	"keep an eye on": "Kad baeluh min", "eye lash": "ramoosh", "eyebrow": "haegib", "eyelid": "gifn"}

	return dict_e

def f_dict():

	dict_f = {"face": "wishsh", "face - confront": "waegih", "facing": ["fi wishsh", "'uSaad"], "fact": "ha'ee'a", "faculty - college": "kulliyya",
	"fade": "bahat", "faggot": "shaKs shazz", "fail - go wrong": "fashal", "fail - in exam": "si'iT", "fail - in life": "Kaeb", 
	"failure - in life": ["fashal", "Kayba"], "failure - in exam": "suQooT", "failure - person": ["faeshil", "Kaeyib"], 
	"faint (v inf)": "saKsaK", "faint (adj)": "misaKsaK", "fair - reasonable": "Aaedil", "fair skinned": "'abyaDaani", "faith": "'ieemaen",
	"faithful": "wafi", "fake": ["ta'leed", "falSw", "baaTil", "mit'allid"], "fall (into) (v inf)": "wi'iA", "fall (n s)": "wa'Aa",
	"fall asleep": "niAis", "fall down": "wi'iA", "false": "falSw", "false (adj)": "GalaT", "familiar (with)": "m'aloof", "family (n)": "Aayla",
	"family (adj)": "Aae'ili", "famous": "mashhoor", "fan - admirer": "muAgab", "fan - enthusiast": "Gaewi", "fan": "marwaha", "fancy": "habb", 
	"fantastic": ["haeyil", "mahool"], "far / far away": "baAeed", "farewell": "waddaA", "fart (n s)": ["DarTa", "taZreeT"], 
	"fart (vi inf)": ["ZarraT", "gayyas", "fassa"] ,"farther": "'abAad", "fascinating": ["muzhil", "mubhir"], "fast": "sareeA - bisurAa",
	"faster": "'asraA", "fasting": "Siyaem - Soom", "(become) fat": "tiKin", "fat": "tiKeen", "fate": "Qadar", "father": "'abb", 
	"fathom": "fihim", "fatigue": "taAb", "faucet": "hanafiyya", "fault - blame": "zanb", "favour (n)": ["Kidma", "Talab"], 
	"favourite / favourable - also prefer": "mufaDDal", "favouritism": "tahayyiz", "fear": "Kaef - Koof", "fearing": 
	"Kaayif", "feast - religious holiday": "Aeed", "feature": "meeza", "(becoming) fed up": "'arfaan", "bored": "zah'aen", 
	"(become) fed up (with)": ["'irif", "zihi'"], "fee": "rusoom", "feed": "'akkil", "feel - emotion": "hass", "feel hot": "harraan", 
	"feel like - in the mood for...": "nifs", "feel the effect": "t'aaththar", "feeling (n s)": "'ihsaes", "feeling (adj)": "haesis", 
	"hurt (someone's) feelings": "garah", "fetch": "gaeb", "fellow": ["raggil", "work - zameel"], "female - human (n)": "'untha", 
	"fever": ["humma", "suKooniyya"], "feverish": "saKnaen", "few": "shuwaya", "(a) few": "shuwayit", "fewer": "'a'all", "fiance": "KaTeeb", 
	"fiancee": "KaTeeba", "fierce": "Aabeef", "fifteen": "Kamastaashar", "fifth": "Kaemis", "fifty": "Kamseen", "fight (n s)": "Kinae'a", 
	"fight (with) (v inf)": "'itKaeni'", "fight - war (v)": "haerib", "fighter": "muhaerib", "figure - shape of woman": "ta'seem", "fig": "teen",
	"figure - work out": "Qarrar", "fill out - form": "maleet", "filled (adj)": "maleeaen", "film": "feelm", "filth": "wasaeKa", "final": "nihae'i", 
	"finally": "'aKeeran", "finance (v inf)": "mawwil", "financial": "maddi", "financing": "tamweel", "find - locate": "lee'i", "find - search for": "dawwar", 
	"find out": "'iktishif", "finding - result": "nateega", "fine - good": ["kuwayis", "Tayyib"], "finger": "SubaaA", "fingernail": "Dufr", "finish": "KiliS", 
	"finish - end": "nihaeya", "(be) finished (vi inf)": ["'intaha", "KiliS"], "finished - none left": ["KaaliS", "KalSaan"], "finished - completed": "kaemil",
	"fire - flame": "naar", "fire - dismiss": ["rafad", "Tarrad"], "fire - gun": "Darrab narr", "fire - on fire": "waeliA", "(be) fired": "'itrafad", "firm - solid": "naeshif", 
	"firm - certain": "'akeed", "firmly": "bihazm", "first": "'awwil", "(the) first": "il 'awwil", "firstly": "'awalan", "fish (n s)": "samak", "fish (v inf)": "Saad - Saayid", 
	"fish bone": "shook ilsamak", "fisherman": "Sayyaad", "fist": "QabDa", "fit - right size": "maZbooT", "fit - suitability": "mula'm", 
	"fit - health": "rasheeQ", "fitness": "ilyaaQa", "five": "Kamsa", "five hundred": "Kumsumiyya", "fix - attach": "thabbat", "fix - repair": "Sallah", 
	"fixing - repair": "taSleeh", "fixing - installation": "tarkeeb", "flame": "naar", "flash": "flaesh", "flattery - kind comments": "madh",
	"flattery - to get something": "tamalluQ", "flaw": "Aeeb", "flee": "hirib", "flesh": "lahm", "flexibility (adv)": "muroona", 
	"flexibility (n s)": "ilyoona", "flexible": "marin", "flight - fleeing": "huroob", "flight - trip": ["rihla gawayya", "rihla Tayaraan"], 
	"flight - flying": "Tayaraan", "flight attendant": "muDeef Tayaraan", "flip flop": "shibshib", "flirt (with) (v inf)": ["Aaekis", "baSbaS"],
	"flirt (n)": "Aeel'", "flirty": "Aeel'", "float (n s)": "Aawwaema", "float (v inf)": "Aaem", "flood (n s)": "fayaDaan", 
	"flood - something (v inf)": "Garra'", "flood - overflow (v inf)": "faaD", "(be) flooded": "Giri'", "floor - in building": "door", 
	"floor - of a room": "'arD", "flour": "di'ee'", "flow (vi inf)": "gara", "flow (n)": "garayaen", "flower": "ward", "flu": "inflilwanza", 
	"fluent": "baeriA", "fluently": "biTalaaQa", "fluid": "sae'il", "fluster": "sarbaA", "(be) flustered": "'itsarbaA", "fly (n s)": "dibbaen", 
	"fly (v inf)": "Taar", "flying": "Tayaraan", "foam - on liquid": "raGwa", "foam - on furniture": "fill", "focus (on) - concentrate": "rakkiz", 
	"fog": "shabboora", "fold (v inf)": "Tabba'", "folder": "malaff", "folk - people": "naes", "follow - catch up with": "lihi'", 
	"follow - chase": "Taarid", "follow - understand": "fihim", "follow - instructions": "tabaA", "follow up": "taebiA", "follower": ["taebiA", "tabaA"],
	"following": ["'illi baAd", "wara", "taeil"], "food": "'akl", "fool - deceieve": ["Kamm", "Dihik"], "fool - silly person": "AabeeT", 
	"foolish - stupid": ["'ahbal", "Gabi", "bahlool"], "foolishness": "masKara", "foot": "rigl", "football": "koora", "for - intended for": "Aalashaen",
	"for - in favour for": "maAa", "for - because": "Aalashaen", "for - so": ["li", "Aala", "fi"], "for - period of time for now": "min", 
	"for example": "biSuwra", "forbid - something": "manaA", "forbidden": "mamnooA", "forbidding": "manA", "(by) force": "biilAafya", 
	"power - force (energy)": "Quwwa", "force (v inf)": ["gabar", "'agbar"], "force - pressure": "DaGt", "forced (part)": "muDTar", 
	"(be) forced (v inf)": "'itgabar", "forehead": ["gibeen", "'oora", "gabha"], "foreign": "'agnabi", "foreigner": "'agnabi", 
	"foremost": "'ahamm", "forsee": "tawaQQaA", "forever": "lil'abad", "forge - counterfeit": "zawwar", "forget": "nisi", "forget it": "'i'lib",
	"forgetting": "nisyaen", "forgive - one another": "'itsaemih", "forgiveness": "musaamaha", "forgotten": "naesi", "fork": "shooka", 
	"form - appearance": "shakl", "formal": ["rasmi", "shakli"], "formality": "'igra' shakla", "format": "binya", "former": "'abli", "formulate": "KaTTaT", 
	"forsaken": "mahgoor", "forthcoming - information": "Sareeh", "fortunate": "mahZooZ", "fortunately": "lihusn ilhaZZ", "fortune - wealth": "tharwa",
	"forty": "'arbiAeen", "forum": "'igtimaeA", "foward - direction": "uddaem", "foward - presumptuous": "bagaeha", "fossil": "'ahfoora",
	"fountain": "nafoora", "four": "'arbaAa", "fourteen": "'arbaAa Aashara", "fourth": "rabbiA", "fraction": "guz'", "fragile": "Qaabil likasr",
	"fragment": "hitta", "frame - picture": "birwaez", "France": "faransa", "frank": ["Sareeh", "duGri"], "frankly": "biSaraaha", "fraud": "talaeAub", 
	"(become) free": "fiDi", "free - not busy": "faaDi"}